# Generated by Django 4.1.7 on 2023-08-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_rename_colorpicker_homepageproduct_color"),
        ("telegram_app", "0002_alter_returns_options_alter_returns_card_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusProducts",
            fields=[
                (
                    "uid",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Номер Возврата",
                    ),
                ),
                (
                    "bonus_count",
                    models.IntegerField(
                        verbose_name="Количество бонусов на получение товара"
                    ),
                ),
                ("products", models.ManyToManyField(to="main.product")),
            ],
            options={
                "verbose_name": "Товары на бонус систем",
                "verbose_name_plural": "Товары на бонус систем",
            },
        ),
    ]
