# Generated by Django 4.1.7 on 2023-08-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_app", "0005_alter_user_bonus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bonus_number",
            field=models.IntegerField(default=0, verbose_name="Кол-во бонус-покупок"),
        ),
    ]
