# Generated by Django 4.1.7 on 2023-09-03 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_app", "0007_user_used_promo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="promocode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="telegram_app.promocode",
                verbose_name="Промокод при оформлении заказа",
            ),
        ),
        migrations.AlterField(
            model_name="returns",
            name="number_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="telegram_app.order",
                verbose_name="Номер заказа от которого идет возврат",
            ),
        ),
        migrations.AlterField(
            model_name="returns",
            name="promocode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="telegram_app.promocode",
                verbose_name="Промокод при оформлении заказа",
            ),
        ),
    ]
