# Generated by Django 4.1.7 on 2023-09-03 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "telegram_app",
            "0008_alter_order_promocode_alter_returns_number_order_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="id покупателя в telegram",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="promocode",
            field=models.CharField(
                max_length=40,
                verbose_name="Промокод (Промокоды лучше не удалять только в крайней мере, тк у заказов где был промокод вместо него будет null)",
            ),
        ),
        migrations.AlterField(
            model_name="returns",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="id покупателя в telegram",
            ),
        ),
    ]
