# Generated by Django 4.1.7 on 2023-07-19 18:02

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Название брэнда",
                    ),
                ),
                (
                    "font",
                    models.ImageField(
                        upload_to="font_brand/", verbose_name="Фото брэнда"
                    ),
                ),
                (
                    "rarity",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="Рарность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренды",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "colorpicker",
                    colorfield.fields.ColorField(
                        default="#FF0000",
                        image_field=None,
                        max_length=18,
                        samples=None,
                        verbose_name="Выбор цвета для отображения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цвет",
                "verbose_name_plural": "Цвета",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Материал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
            },
        ),
        migrations.CreateModel(
            name="Podcategory",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Подкатегория",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("shoe", "Обувь"),
                            ("cloths", "Одежда"),
                            ("bags", "Сумки"),
                            ("clocks", "Часы"),
                            ("accessories", "Аксессуары"),
                            ("cosmetics", "Косметика"),
                            ("technique", "Техника"),
                            ("toys", "Игрушки"),
                            ("sport", "Спорт"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("shoe", "Обувь"),
                            ("cloths", "Одежда"),
                            ("bags", "Сумки"),
                            ("clocks", "Часы"),
                            ("accessories", "Аксессуары"),
                            ("cosmetics", "Косметика"),
                            ("technique", "Техника"),
                            ("toys", "Игрушки"),
                            ("sport", "Спорт"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "composition",
                    models.TextField(blank=True, null=True, verbose_name="Состав"),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Содержание"),
                ),
                (
                    "sizechart",
                    models.ImageField(
                        upload_to="size_chart/", verbose_name="Размерная сетка"
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_images/",
                        verbose_name="Картинка #1",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_images/",
                        verbose_name="Картинка #2",
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_images/",
                        verbose_name="Картинка #3",
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_images/",
                        verbose_name="Картинка #4",
                    ),
                ),
                (
                    "image5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_images/",
                        verbose_name="Картинка #5",
                    ),
                ),
                (
                    "image6",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_images/",
                        verbose_name="Картинка #6",
                    ),
                ),
                (
                    "popularity",
                    models.IntegerField(default=0, verbose_name="Популярность"),
                ),
                ("prices", models.JSONField(default=dict, verbose_name="Цены")),
                (
                    "min_price",
                    models.IntegerField(default=0, verbose_name="Минимальная цена"),
                ),
                (
                    "max_price",
                    models.IntegerField(default=0, verbose_name="Максимальная цена"),
                ),
                (
                    "data_create",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата добавления товара (автоматически)",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.color",
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.material",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "podcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.podcategory",
                        verbose_name="Подкатегория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="HomePageProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.ImageField(
                        upload_to="main/",
                        verbose_name="Фото, что будет сверху (при нажатии будет переводить на 'Товар #1'",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.brand"
                    ),
                ),
                (
                    "product1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product1",
                        to="main.product",
                        verbose_name="Товар #1",
                    ),
                ),
                (
                    "product2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product2",
                        to="main.product",
                        verbose_name="Товар #2",
                    ),
                ),
                (
                    "product3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product3",
                        to="main.product",
                        verbose_name="Товар #3",
                    ),
                ),
                (
                    "product4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product4",
                        to="main.product",
                        verbose_name="Товар #4",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товары на главной странице",
                "verbose_name_plural": "Товары на главной странице",
            },
        ),
    ]
