# Generated by Django 4.1.7 on 2023-07-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="type_size",
            field=models.CharField(
                blank=True,
                max_length=20,
                verbose_name="Тип размера товара(Необязательно)",
            ),
        ),
    ]
