# Generated by Django 4.1.7 on 2023-07-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_product_type_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Recomendation",
            field=models.JSONField(default=dict, verbose_name="Рекомендации"),
        ),
    ]
