# Generated by Django 4.1.7 on 2023-07-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_product_recomendation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Recomendation",
            field=models.JSONField(blank=True, verbose_name="Рекомендации"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="Название (нельзя '#')"
            ),
        ),
    ]
