# Generated by Django 4.1.7 on 2023-07-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_remove_homepageproduct_url_product_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcategoryBrandforNav",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("shoe", "Обувь"),
                            ("cloths", "Одежда"),
                            ("bags", "Сумки"),
                            ("clocks", "Часы"),
                            ("accessories", "Аксессуары"),
                            ("cosmetics", "Косметика"),
                            ("technique", "Техника"),
                            ("toys", "Игрушки"),
                            ("sport", "Спорт"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "recreate",
                    models.BooleanField(default=False, verbose_name="Пересоздать"),
                ),
                (
                    "Brand",
                    models.ManyToManyField(
                        to="main.brand", verbose_name="Бренды в меню"
                    ),
                ),
                (
                    "podcategory",
                    models.ManyToManyField(
                        limit_choices_to={
                            "category": models.CharField(
                                choices=[
                                    ("shoe", "Обувь"),
                                    ("cloths", "Одежда"),
                                    ("bags", "Сумки"),
                                    ("clocks", "Часы"),
                                    ("accessories", "Аксессуары"),
                                    ("cosmetics", "Косметика"),
                                    ("technique", "Техника"),
                                    ("toys", "Игрушки"),
                                    ("sport", "Спорт"),
                                ],
                                max_length=20,
                                verbose_name="Категория",
                            )
                        },
                        to="main.podcategory",
                        verbose_name="Подкатегории в меню",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегории и Бренды для меню",
                "verbose_name_plural": "Подкатегории и Бренды для меню",
            },
        ),
    ]
