# Generated by Django 4.1.7 on 2023-07-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_podcategorybrandfornav_delete_newpageproduct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcategorybrandfornav",
            name="recreate",
        ),
        migrations.AlterField(
            model_name="podcategorybrandfornav",
            name="Brand",
            field=models.ManyToManyField(
                blank=True, to="main.brand", verbose_name="Бренды в меню"
            ),
        ),
        migrations.AlterField(
            model_name="podcategorybrandfornav",
            name="podcategory",
            field=models.ManyToManyField(
                blank=True, to="main.podcategory", verbose_name="Подкатегории в меню"
            ),
        ),
    ]
