# Generated by Django 4.1.7 on 2023-08-03 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_remove_podcategorybrandfornav_recreate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepageproduct",
            name="product4",
        ),
        migrations.AlterField(
            model_name="homepageproduct",
            name="product1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product2",
                to="main.product",
                verbose_name="Товар #1",
            ),
        ),
        migrations.AlterField(
            model_name="homepageproduct",
            name="product2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product3",
                to="main.product",
                verbose_name="Товар #2",
            ),
        ),
        migrations.AlterField(
            model_name="homepageproduct",
            name="product3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product4",
                to="main.product",
                verbose_name="Товар #3",
            ),
        ),
        migrations.AlterField(
            model_name="homepageproduct",
            name="title",
            field=models.ImageField(
                upload_to="main/",
                verbose_name="Фото, что будет сверху (при нажатии будет переводить на бренды)",
            ),
        ),
    ]
