# Generated by Django 4.1.7 on 2023-08-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_rename_colorpicker_homepageproduct_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepageproduct",
            name="title",
            field=models.ImageField(
                upload_to="main/",
                verbose_name="Фото, что будет сверху (при нажатии будет переводить на бренд)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image1",
            field=models.ImageField(
                upload_to="product_images/", verbose_name="Картинка #1"
            ),
        ),
    ]
