# Generated by Django 4.1.7 on 2023-08-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_alter_homepageproduct_title_alter_product_image1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ManyToManyField(to="main.color", verbose_name="Цвет"),
        ),
    ]
