# Generated by Django 4.1.7 on 2023-09-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_remove_product_color_product_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sizechart",
            field=models.ImageField(
                upload_to="size_chart/",
                verbose_name="Размерная сетка (изначально в ~600px)",
            ),
        ),
    ]
